#
# production configuration
#
mybatis:
   config-location: classpath:mybatis/configuration.xml

spring:
   datasource:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mysql://34.64.148.106:3307/return0?characterEncoding=utf8
      username: return0
      password: 1234

eureka:
   instance:
      preferIpAddress: true
   client:
      fetchRegistry: true
      registerWithEureka: true
      serviceUrl:
         defaultZone: http://34.64.240.101:8761/eureka
